### ISSUE TITLE
[Help wanted] Only some assets drawn in Esoteric example project

### ISSUE THREAD

**Issue by lardois** [maxgribov/Spine#18]
Hi and thanks for the great library. Just trying to get familiar with it and run into problem...

Downloaded Spine Trial from Esoteric home page. There are some examples included. Tried to get "owl" example running.

Created asset folder named "Owl" and added Sprite Atlas named "default" under it. "Provides namespace" are crossed in both. Then dropped all the assets from "owl" "images" folder into that Sprite Atlas.

<img width="811" alt="screenshot 2019-02-05 at 20 09 50" src="https://user-images.githubusercontent.com/9699852/52294444-0c475700-2982-11e9-9090-684a09bc8f25.png">

There's no directory structure in Owl Spine project, so no need for other atlases besides "default" I think?

<img width="1014" alt="screenshot 2019-02-05 at 19 58 13" src="https://user-images.githubusercontent.com/9699852/52294150-32b8c280-2981-11e9-825f-724525c5f8ac.png">

The core is relatively simple, copied from the example:

```
class MainScene: SKScene {
    
    override func didMove(to view: SKView) {
        
        backgroundColor = .white
        
        if let character = Skeleton(fromJSON: "owl-pro", atlas: "Owl", skin: "default"){
            
            character.position = CGPoint(x: self.size.width / 2, y: (self.size.height / 2))
            character.setScale(0.2)
            
            self.addChild(character)
            
            if let idleAnimation = character.animation(named: "idle") {
                character.run(SKAction.repeatForever(idleAnimation))
            }
        }
    }
}
```

However, only some of the assets are drawn (and animated). Can't figure out why these ones, but not others.

![screenshot 2019-02-05 at 19 29 33](https://user-images.githubusercontent.com/9699852/52293661-1405fc00-2980-11e9-98be-49bc46384ca9.png)

Asset names should be correct, they're the same as in Spine project and JSON file.

Tried also to copy images from "1x" to "2x" and "3x" also with no help.

What might be the problem? And how could I debug this kind of problems?

**Comment by maxgribov** [comment]
Try to start by following step by step on this guide:
https://github.com/maxgribov/Spine/wiki/Assets

**Comment by lardois** [comment]
Hi, have read the guide very carefully, but can't still see what is wrong here.

**Comment by maxgribov** [comment]
are namespaces enabled for the folder `Owl` and atlas `default`?

<img width="500" alt="spine_readme_assets_namespace" src="https://user-images.githubusercontent.com/6514571/52295530-2175b300-298d-11e9-9e28-28d5fe7e97a2.png">

**Comment by lardois** [comment]
Yes they are, as noted...
Could it be because of some missing feature in example file? There are some "mesh" keys in JSON file...

**Comment by maxgribov** [comment]
By the way, if you used meshes in the Spine App that could be a problem there. Meshes are currently not supported by library and I do not know to whom effect they can lead.

**Comment by lardois** [comment]
Yeah, it seems it was because of the mesh feature.
Noticed now that Spine examples that have "pro" extension use pro features, such as Mesh. the ones with "ess" in file name are done with some "lite" feature set and these examples work fine.

**Comment by maxgribov** [comment]
Yup... Sorry but I still can't find the time to implement mesh support...
