### ISSUE TITLE
Spine resource loading

### ISSUE THREAD

**Issue by al1020119** [maxgribov/Spine#20]
Hello, I'm a loyal user of your Spine. First of all, thank you for providing a very good library, but I need your help.

https://github.com/maxgribov/Spine

We have shown Skeleton properly, previously because of the version problem of our Spine. But when we are ready to start, we encounter another problem, that is, the problem of loading resources. Our picture or JSON file resources are real servers。

In this way,

https://github.com/maxgribov/Spine/wiki/Assets

operations are not possible, and we often have resource updates or additions, which will cause us to need to repackage every time.

So, may I ask, what better solution is there, or can we solve the problem of this resource?

**Comment by maxgribov** [comment]
please check this issue: https://github.com/maxgribov/Spine/issues/16
there I described the way how to load assets dynamically from the code when creating atlases in runtime.
