### ISSUE TITLE
exporting setting

### ISSUE THREAD

**Issue by mash3l777** [maxgribov/Spine#24]
can you shows us exporting setting in spine.

**Comment by maxgribov** [comment]
you mean these settings?
<img width="623" alt="Screenshot 2019-08-25 at 22 02 23" src="https://user-images.githubusercontent.com/6514571/63654535-362c6380-c784-11e9-8436-38afdcbfb73f.png">

**Comment by mash3l777** [comment]
Yes this settings, because they can’t read Json file

**Comment by maxgribov** [comment]
What Spine version do you use?

**Comment by mash3l777** [comment]
Pro Last version

**Comment by maxgribov** [comment]
version number please

**Comment by mash3l777** [comment]
spine Pro V3.8.72

**Comment by maxgribov** [comment]
OK, the problem is due to the fact that in Spine version 3.8.x JSON format has changed. Look this issue: #25 
for now you can use fork from @unboxme : https://github.com/unboxme/Spine/commits/spine-3.8.x
or just wait when I'll find time to implement new JSON format support
