### ISSUE TITLE
Spine 3.8.Х сompatibility

### ISSUE THREAD

**Issue by unboxme** [maxgribov/Spine#25]
Hey,

This framework is awesome! Thank you!

But a month ago EsotericSoftware released new version. And there are some new changes in JSON file:
– `skeleton` without `width` param;
– `animations` with new `c2` and `c3` params and `curve` is a single value, not an array.

Do you plan to update it?

**Comment by maxgribov** [comment]
I need to see how much work is needed. I can't say for sure if I'll be able to do it any time soon.

**Comment by markst** [comment]
Is this possibly related to the json failing decode?

**Comment by maxgribov** [comment]
it seems that not all these changes in JSON have been documented yet: http://esotericsoftware.com/spine-json-format#Deform-timeline
I see these `c1`, `c2`,` c3`, `c4`... but at the same time and `"curve": [ 0.25, 0, 0.75, 1 ]`... and  `skeleton` still with `width` param...

**Comment by unboxme** [comment]
Yes, `width` param still is. It was a Spine export bug, never mind.

Anyway you can check my fork [spine-3.8.x](https://github.com/unboxme/Spine/commits/spine-3.8.x) and use this code to update you framework. It works fine with Spine 3.8.68.

We also fixed very important bug with searching textures [here](https://github.com/unboxme/Spine/commit/7e73daeaa73a08f4f08626ce0a693e18f5e551a7).

**Comment by maxgribov** [comment]
@unboxme it would be cool if you send a pull request. And please cover with tests any model changes.

>We also fixed very important bug with searching textures

Surprisingly that it at all works with this bug :)

**Comment by markst** [comment]
@unboxme having only some of my textures appearing using fork. not 100% sure if it's my issue or not currently

**Comment by unboxme** [comment]
@markst It sounds strange. How can I reproduce this bug?
I also found an interesting issue with sprite atlas packaging - it doesn't work as it should with Adobe RGB (1998) color space for non debug schemes. Xcode just ignores some files. And as a result some images for bones can be missed.

**Comment by markst** [comment]
@unboxme here's the resource: ---

not been able to try out changing the colour space. is this something I can do from Xcode xcassets? or do I need to re-export my pngs?

**Comment by maxgribov** [comment]
@markst this can happen if you used meshes in a Spine project like in this issue: #18

**Comment by OdNairy** [comment]
Are there any updates on 3.8 support?
