### ISSUE TITLE
Layers issue

### ISSUE THREAD

**Issue by abaleanu** [maxgribov/Spine#32]
![Screen Shot 2020-03-31 at 16 17 11](https://user-images.githubusercontent.com/50408351/78030675-23f25380-736b-11ea-8ec6-097be8309831.png)
Hello, can you tell me what can be the problem? The animation is ok in spine and in the video preview, when we integrate in the game the layers' order is broken... 
![Screen Shot 2020-03-31 at 16 20 03](https://user-images.githubusercontent.com/50408351/78030926-8186a000-736b-11ea-8149-1940804f3fb7.png) the book for woman should be behind her

**Comment by maxgribov** [comment]
looks like something wrong with layers order... what version of Spine are you use?

**Comment by maxgribov** [comment]
Do you use layers order animation? Or it is static all the time?
