### ISSUE TITLE
Question: getting [SKTexture] instead of Action

### ISSUE THREAD

**Issue by Ideafix0** [maxgribov/Spine#33]
Is there a way we can get a list of textures instead of an action when animating an object?
Can we add an extension do to that?
Thank you

**Comment by maxgribov** [comment]
can you explain in more detail what you want?

**Comment by Ideafix0** [comment]
As a way of animating a character, you have:

if let walkAnimation = character.animation(named: "walk") {

    character.run(walkAnimation)
}

I was aiming for something like:

if let walkAnimationFrame : [SKTexture] = character.animationAsTextureVector(named: "walk") {
  ...
}
The goal would be to obtain the animation frames as a sequence of textures.


Thank you for your time.

**Comment by maxgribov** [comment]
theoretically you can render each frame of animation for your character and get it in the form of texture. But I don't see any practical sense in this. Why do this when you can just play the animation?

and of course I don't plan to add anything like this to the library.. But if you really need it, you can do it yourself... The code is open...

**Comment by Ideafix0** [comment]
Animations based on actions have the assumption that the amount of time per frame is constant, which is not always the case. In those cases, there is the need to control the animation rate (which is variable).

**Comment by maxgribov** [comment]
actually, with Spine, you have full control over the time of each animation. You set the keyframes at exactly the right moment...

**Comment by Ideafix0** [comment]
You do, but that is before generating the animation. On certain sequences, where animation rate depends on other variables then time (e.x. distance from something) the frame rate control is "on the fly"

**Comment by maxgribov** [comment]
you can adjust the animation keyframes themselves to fit the timings you need... and it will be much easier than rendering the animation frames as textures...

**Comment by Ideafix0** [comment]
The timings may change mid animation (i.e. when the animation is already playing). With an action you can't do that.

**Comment by maxgribov** [comment]
by the way, you can control the speed of `SKAction` with property `speed`

**Comment by Ideafix0** [comment]
Depending on the model, it may not be practical.

**Comment by maxgribov** [comment]
I understand that you have some very specific tasks that go beyond my plans for the development of this library... So I'm sorry, but you'll have to come up with something yourself... Good luck

**Comment by Ideafix0** [comment]
Thank you for your time.

On 30 Apr 2020, at 00:01, Max Gribov <notifications@github.com> wrote:

﻿
I understand that you have some very specific tasks that go beyond my plans for the development of this library... So I'm sorry, but you'll have to come up with something yourself... Good luck

**Comment by maxgribov** [comment]
by the way, you can always render your animations as png images directly from the Spine app. Assemble them into sprite sheets and use them as normal sprite animation.

**Comment by Ideafix0** [comment]
That’s what I’m currently doing, and the iOS app payload is too big, even with highly compacted texture atlases. Hence the need to use such a library.

Btw, exactly where in your code are the textures being generated?

On 30 Apr 2020, at 00:05, Max Gribov <notifications@github.com> wrote:

﻿
by the way, you can always render your animations as png images directly from the Spine app. Assemble them into sprite sheets and use them as normal sprite animation.

**Comment by maxgribov** [comment]
> Btw, exactly where in your code are the textures being generated?

Nowhere. Right now, textures are just loaded from assets.
