### ISSUE TITLE
Change the particular skin attachment

### ISSUE THREAD

**Issue by RacingWang** [maxgribov/Spine#40]
Is it possible to change the particular skin attachment in run time?
For example, I'd like to implement an avatar system, so users can change the weapon, shoes, hat or clothes on-demand. (Not just change the whole skin)
How can I achieve this function by Spine?

**Comment by iusn** [comment]
hello do you have to solve it?

**Comment by MarvelzDJ** [comment]
Would really love to know if this is possible. Love this library but easily changing weapons or anything would be insanely helpful

**Comment by maxgribov** [comment]
working on this in v3 branch
