### ISSUE TITLE
Is this supported use .atlas to  separate  packed image.

### ISSUE THREAD

**Issue by koalahl** [maxgribov/Spine#41]
with new Spine app , we export project as below picture:
![image](https://user-images.githubusercontent.com/16068616/96207829-c5a36000-0f9e-11eb-9487-7bd379416841.png)

xxx.json
xxx.atlas
xxx.png  ---> packed image
but , this framework  seems not support packed image.

Any update for this feature?

**Comment by maxgribov** [comment]
No, it doesn't. Please read this: https://github.com/maxgribov/Spine/wiki/Assets

**Comment by cmitjans-at-wiris** [comment]
Hello, is there any work put into supporting this?
Thank you!

**Comment by maxgribov** [comment]
No, and not planned.
