### ISSUE TITLE
[HELP] How uses network image resources

### ISSUE THREAD

**Issue by lforme** [maxgribov/Spine#42]
Please give me an example
I want to load a network image resource to replace the local .spriteatlas

**Comment by NikolayJuly** [comment]
I see that there is init of SKTextureAtlas' map. And SKTexture can be initialised at runtime with map of images.
Looks like this is easiest way to use downloaded skins.

**Comment by lforme** [comment]
> I see that there is init of SKTextureAtlas' map. And SKTexture can be initialised at runtime with map of images.
> Looks like this is easiest way to use downloaded skins.

I have solved it ~_~ thanks
