### ISSUE TITLE
[HELP]Character display is incomplete

### ISSUE THREAD

**Issue by sunyunfei** [maxgribov/Spine#43]
Hello, I followed your prompt steps to integrate, but the characters with realistic running effects are not complete. The pictures directly exported from the spiner are directly under a folder and are not classified.
<img width="270" alt="截屏2021-05-27 14 11 17" src="https://user-images.githubusercontent.com/12780752/119775383-1ba59200-bef6-11eb-8c08-6c456301e7e2.png">
![Simulator Screen Shot - iPhone 12 - 2021-05-27 at 14 10 57](https://user-images.githubusercontent.com/12780752/119775413-23fdcd00-bef6-11eb-9a16-6822e90514eb.png)
![截屏2021-05-27 14 17 37](https://user-images.githubusercontent.com/12780752/119775658-7fc85600-bef6-11eb-9be8-59cae3f19aaf.png)

**Comment by maxgribov** [comment]
it looks like the Spine project, you trying to convert, uses meshes. This library does not supports meshes.

**Comment by kvaDrug** [comment]
@maxgribov, did you add mesh support?

**Comment by maxgribov** [comment]
no
