### ISSUE TITLE
V3 - multiple build errors (SpriteKit not imported)

### ISSUE THREAD

**Issue by kvaDrug** [maxgribov/Spine#48]
Since the last update I got multiple build errors like `Cannot find 'CGFloat'` (see below). Inspecting module files shows that they miss `SpriteKit` import. Probably it was automatically imported on your local Xcode, but it doesn't work on mine and produce these errors. 

>/.../Library/Developer/Xcode/DerivedData/MyProj-dztgcjnsotghztdkvsofoblrksij/SourcePackages/checkouts/Spine/Sources/Spine/Model/Animation/Keyframes/Bone/BoneKeyframeShearModel.swift:13:16: Cannot find type 'CGVector' in scope

>/.../Library/Developer/Xcode/DerivedData/MyProj-dztgcjnsotghztdkvsofoblrksij/SourcePackages/checkouts/Spine/Sources/Spine/Model/Animation/Keyframes/Bone/BoneKeyframeShearModel.swift:30:48: Cannot find 'CGFloat' in scope

>/...Library/Developer/Xcode/DerivedData/MyProj-dztgcjnsotghztdkvsofoblrksij/SourcePackages/checkouts/Spine/Sources/Spine/Model/Animation/Keyframes/Bone/BoneKeyframeShearModel.swift:31:48: Cannot find 'CGFloat' in scope

>/.../Library/Developer/Xcode/DerivedData/MyProj-dztgcjnsotghztdkvsofoblrksij/SourcePackages/checkouts/Spine/Sources/Spine/Extensions Public/Skeleton+Points.swift:28:18: Generic parameter 'ElementOfResult' could not be inferred

**Comment by maxgribov** [comment]
Check if this PR fixes your errors: [build-errors-fix](https://github.com/maxgribov/Spine/pull/49).
