### ISSUE TITLE
Some bugs in function action(_ keyframes: [SlotKeyframeColorModel], _ slot: String)

### ISSUE THREAD

**Issue by ACFancy** [maxgribov/Spine#50]
- Some bugs in function action(_ model: SlotAnimationModel)
  - some animations like  fade, unexpected behavior 
  - before V3 adapted version, the implementation of SlotKeyframeColorModel class was differently. before was excepted behavior
  - e.g:
     ```
      func updated(channel: ColorChannel, index: Int) -> SKColor {
        
        guard channel >= 0, channel <= 1 else { return self }
        
        switch index {
        case 0: return updated(red: channel)
        case 1: return updated(green: channel)
        case 2: return updated(blue: channel)
        case 4: return updated(alpha: channel) // case 4 should be 3
        default: return self
        }
    }
    ```

**Comment by maxgribov** [comment]
@ACFancy this is great that you reported this bug and even found reason of it, but where is pull request from you?

**Comment by maxgribov** [comment]
@ACFancy  can you test if this PR #51 fixes the bug?

**Comment by ACFancy** [comment]
@maxgribov 
- there was one of some bugs fixed
- But others in some animations. like fade, unexpected behavior,  spine animation to hide, maybe alpha was changed to zero, but always show in new version tag code.
- some issue [51](https://github.com/maxgribov/Spine/pull/51#issuecomment-1556763981)
