### ISSUE TITLE
I run the examples successfully but why no goblin shows on?

### ISSUE THREAD

**Issue by QTIGER2** [maxgribov/Spine#63]
Please anybody can help me? I download the example project and build it successfully. But when the app run on the simulator, no goblin shows on the screen! I dont know what's wrong?

some info:
xcode version: 15
simulator: iphone 15 pro
ios:17.2

background: black
nodes count:42
draws count:1
fps:60

<img width="396" alt="image" src="https://github.com/maxgribov/Spine/assets/49549001/5463801d-e66e-42e1-8ab8-89a1a4522a43">

**Comment by QTIGER2** [comment]
I know whats wrong, the folder is  "Goblins", not "goblins"!!!!!

**Comment by maxgribov** [comment]
yes, there was a problem with `goblins`  folder name. For some reason in my local repo it was correct but on remote not. Just reset repo. You can clone it again and everything should work.

**Comment by QTIGER2** [comment]
> yes, there was a problem with `goblins` folder name. For some reason in my local repo it was correct but on remote not. Just reset repo. You can clone it again and everything should work.

Thanks for your reply！But now I have another problem，the photos in Assets Wiki page “https://github.com/maxgribov/Spine/wiki/Assets#sprite-atlases” have been corrupted！Can u please repair it？

**Comment by maxgribov** [comment]
> Can u please repair it？

done

**Comment by QTIGER2** [comment]
> > Can u please repair it？
> 
> done

Thanks a lot！😃
